name: Docs
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - name: gen-docs
        run: zig build docs
      - name: upload-artifact
        uses: actions/upload-artifact@main
        with:
          name: sokol-zig-docs
          path: zig-out/docs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: floooh/sokol-zig-docs
          ssh-key: ${{secrets.SOKOL_ZIG_DOCS_DEPLOY}}
      - uses: actions/download-artifact@main
        with:
          name: sokol-zig-docs
      - name: "commit and push"
        run: |
          git config user.email "none"
          git config user.name "GH Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "updated (${{ github.run_number }})"
          git push
